# Generated by Django 4.0.1 on 2022-01-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('memeber_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.member', verbose_name='prdo?')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=50, null=True)),
                ('code', models.CharField(blank=True, db_column='code', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
                ('call', models.CharField(blank=True, db_column='call', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=50, null=True)),
                ('date', models.CharField(blank=True, db_column='date', max_length=50, null=True)),
                ('type', models.CharField(blank=True, db_column='type', max_length=50, null=True)),
                ('transport_no', models.CharField(blank=True, db_column='transport_no', max_length=50, null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='pro_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'pro_category',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
                ('price', models.CharField(blank=True, db_column='price', max_length=50, null=True)),
                ('stock', models.CharField(blank=True, db_column='stock', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=50, null=True)),
                ('pro_category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.pro_category', verbose_name='prdo?')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='shop_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'shop_category',
            },
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('shop_name', models.CharField(blank=True, db_column='shop_name', max_length=50, null=True)),
                ('manager', models.CharField(blank=True, db_column='manager', max_length=50, null=True)),
                ('shop_phone', models.CharField(blank=True, db_column='shop_phone', max_length=50, null=True)),
                ('shop_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.shop_category', verbose_name='shop_category')),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=50, null=True)),
                ('content', models.CharField(blank=True, db_column='content', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_column='password', max_length=50, null=True)),
                ('memeber_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.member', verbose_name='prdo?')),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='prdo?')),
            ],
            options={
                'db_table': 'qna',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.shop', verbose_name='prdo?'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('pay_method', models.CharField(blank=True, db_column='pay_method', max_length=50, null=True)),
                ('memeber_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.member', verbose_name='prdo?')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('amount', models.CharField(blank=True, db_column='amount', max_length=50, null=True)),
                ('order_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.order', verbose_name='prdo?')),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='prdo?')),
            ],
            options={
                'db_table': 'order-product',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='member_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='prdo?'),
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('opt_name', models.CharField(blank=True, db_column='opt_name', max_length=50, null=True)),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='prdo?')),
            ],
            options={
                'db_table': 'option',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('content', models.CharField(blank=True, db_column='content', max_length=50, null=True)),
                ('rate', models.CharField(blank=True, db_column='rate', max_length=50, null=True)),
                ('memeber_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.member', verbose_name='prdo?')),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='prdo?')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='cart_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('amount', models.CharField(blank=True, db_column='amount', max_length=50, null=True)),
                ('cart_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.cart', verbose_name='prdo?')),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='prdo?')),
            ],
            options={
                'db_table': 'cart-product',
            },
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('ad_name', models.CharField(blank=True, db_column='ad_name', max_length=50, null=True)),
                ('code', models.CharField(blank=True, db_column='code', max_length=50, null=True)),
                ('ad_detail', models.CharField(blank=True, db_column='ad_detail', max_length=50, null=True)),
                ('member_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.member', verbose_name='prdo?')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
