# Generated by Django 4.0.1 on 2022-02-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=50, null=True),
        ),
    ]
