# Generated by Django 4.0.1 on 2022-02-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_order_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='qna_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'qna_category',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='memeber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.member', verbose_name='memeber'),
        ),
        migrations.AlterField(
            model_name='cart_product',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='cart_product',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='memeber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.member', verbose_name='memeber'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='option',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='prdoduct'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='memeber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.member', verbose_name='memeber'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.pro_category', verbose_name='pro_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.shop', verbose_name='shop'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='memeber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='manager',
            field=models.CharField(blank=True, db_column='manager_id', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qna',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.qna_category', verbose_name='category'),
        ),
    ]
