# Generated by Django 4.0.1 on 2022-02-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pro_category_id',
            new_name='pro_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
