# Generated by Django 4.0.1 on 2022-02-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_pro_category_id_product_pro_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='memeber_id',
            new_name='memeber',
        ),
        migrations.RenameField(
            model_name='cart_product',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cart_product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='memeber_id',
            new_name='memeber',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='order_product',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order_product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='memeber_id',
            new_name='memeber',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='memeber_id',
            new_name='memeber',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='product_id',
            new_name='product',
        ),
    ]
