# Generated by Django 4.0.1 on 2022-02-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_qna_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='answer_flag',
            field=models.CharField(blank=True, db_column='answer_flag', default='0', max_length=10, null=True),
        ),
    ]
