# Generated by Django 4.0.1 on 2022-02-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_qna_answer_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='memeber',
            new_name='member',
        ),
    ]
