# Generated by Django 4.0.1 on 2022-03-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_product_main_img_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=50, null=True),
        ),
    ]
