# Generated by Django 4.0.1 on 2022-04-03 04:57

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_order_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
