# Generated by Django 4.0.1 on 2022-04-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_product_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='memeber',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='memeber',
        ),
        migrations.AddField(
            model_name='cart',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.member', verbose_name='member'),
        ),
    ]
