# Generated by Django 4.0.1 on 2022-04-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_cart_memeber_remove_payment_memeber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_img',
            field=models.ImageField(blank=True, null=True, upload_to='comment/main'),
        ),
    ]
