# Generated by Django 4.0.1 on 2022-04-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_comment_comment_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('content', models.CharField(blank=True, db_column='content', max_length=50, null=True)),
                ('comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.comment', verbose_name='comment')),
            ],
            options={
                'db_table': 'comment_reply',
            },
        ),
    ]
