# Generated by Django 4.0.1 on 2022-04-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='memeber',
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.member', verbose_name='member'),
        ),
    ]
