# Generated by Django 4.0.1 on 2022-04-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_comment_memeber_comment_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_flag',
            field=models.CharField(blank=True, db_column='reply_flag', default='0', max_length=10, null=True),
        ),
    ]
