# Generated by Django 4.0.1 on 2022-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_comment_reply_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, db_column='content', null=True),
        ),
    ]
