# Generated by Django 4.0.1 on 2022-04-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='review_flag',
            field=models.CharField(blank=True, db_column='review_flag', default='0', max_length=10, null=True),
        ),
    ]
