# Generated by Django 4.0.1 on 2022-04-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.AddField(
            model_name='comment',
            name='orderproduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.order_product', verbose_name='orderproduct'),
        ),
    ]
