# Generated by Django 4.0.1 on 2022-04-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_remove_comment_product_comment_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.member', verbose_name='member')),
            ],
            options={
                'db_table': 'liked',
            },
        ),
        migrations.CreateModel(
            name='liked_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('liked', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.liked', verbose_name='liked')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='product')),
            ],
            options={
                'db_table': 'liked-product',
            },
        ),
    ]
