# Generated by Django 4.0.1 on 2022-05-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_pro_qna_pro_qna_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_reply',
            name='content',
            field=models.TextField(blank=True, db_column='content', null=True),
        ),
        migrations.AlterField(
            model_name='pro_qna',
            name='content',
            field=models.TextField(blank=True, db_column='content', null=True),
        ),
        migrations.AlterField(
            model_name='qna',
            name='content',
            field=models.TextField(blank=True, db_column='content', null=True),
        ),
    ]
