# Generated by Django 4.0.1 on 2022-05-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_comment_reply_content_alter_pro_qna_content_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pro_category',
            table='pro_subcategory',
        ),
    ]
