# Generated by Django 4.0.1 on 2022-05-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_alter_pro_category_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pro_category',
            new_name='pro_subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_category',
        ),
        migrations.AddField(
            model_name='product',
            name='pro_subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.pro_subcategory', verbose_name='pro_subcategory'),
        ),
    ]
