# Generated by Django 4.0.1 on 2022-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_rename_pro_category_pro_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'pro_category',
            },
        ),
    ]
