# Generated by Django 4.0.1 on 2022-05-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_pro_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_subcategory',
            name='pro_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.pro_category', verbose_name='pro_category'),
        ),
    ]
