# Generated by Django 4.0.1 on 2022-05-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_pro_subcategory_pro_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제시간')),
                ('DeleteFlag', models.CharField(blank=True, db_column='DeleteFlag', default='0', max_length=10, null=True)),
                ('rate', models.IntegerField(blank=True, db_column='rate', null=True)),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.member', verbose_name='member')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='product')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.shop', verbose_name='shop')),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
    ]
