# Generated by Django 4.0.1 on 2022-05-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='call',
            field=models.CharField(blank=True, db_column='call', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='road_ad',
            field=models.CharField(blank=True, db_column='road_ad', max_length=50, null=True),
        ),
    ]
