# Generated by Django 4.0.1 on 2022-01-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_authority', models.CharField(blank=True, db_column='mem_authority', max_length=100, null=True)),
                ('mem_name', models.CharField(blank=True, db_column='mem_name', max_length=100, null=True)),
                ('mem_phone', models.CharField(blank=True, db_column='mem_phone', max_length=100, null=True)),
                ('mem_point', models.CharField(blank=True, db_column='mem_point', max_length=100, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
